// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vector_tile.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VectorTiles.Mvt {

  /// <summary>Holder for reflection information generated from vector_tile.proto</summary>
  internal static partial class VectorTileReflection {

    #region Descriptor
    /// <summary>File descriptor for vector_tile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VectorTileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF2ZWN0b3JfdGlsZS5wcm90bxILdmVjdG9yX3RpbGUiwAQKBFRpbGUSJwoG",
            "bGF5ZXJzGAMgAygLMhcudmVjdG9yX3RpbGUuVGlsZS5MYXllchqhAQoFVmFs",
            "dWUSFAoMc3RyaW5nX3ZhbHVlGAEgASgJEhMKC2Zsb2F0X3ZhbHVlGAIgASgC",
            "EhQKDGRvdWJsZV92YWx1ZRgDIAEoARIRCglpbnRfdmFsdWUYBCABKAMSEgoK",
            "dWludF92YWx1ZRgFIAEoBBISCgpzaW50X3ZhbHVlGAYgASgSEhIKCmJvb2xf",
            "dmFsdWUYByABKAgqCAgIEICAgIACGnMKB0ZlYXR1cmUSDQoCaWQYASABKAQ6",
            "ATASEAoEdGFncxgCIAMoDUICEAESMQoEdHlwZRgDIAEoDjIaLnZlY3Rvcl90",
            "aWxlLlRpbGUuR2VvbVR5cGU6B1VOS05PV04SFAoIZ2VvbWV0cnkYBCADKA1C",
            "AhABGq0BCgVMYXllchISCgd2ZXJzaW9uGA8gAigNOgExEgwKBG5hbWUYASAC",
            "KAkSKwoIZmVhdHVyZXMYAiADKAsyGS52ZWN0b3JfdGlsZS5UaWxlLkZlYXR1",
            "cmUSDAoEa2V5cxgDIAMoCRInCgZ2YWx1ZXMYBCADKAsyFy52ZWN0b3JfdGls",
            "ZS5UaWxlLlZhbHVlEhQKBmV4dGVudBgFIAEoDToENDA5NioICBAQgICAgAIi",
            "PwoIR2VvbVR5cGUSCwoHVU5LTk9XThAAEgkKBVBPSU5UEAESDgoKTElORVNU",
            "UklORxACEgsKB1BPTFlHT04QAyoFCBAQgEBCAkgD"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTiles.Mvt.Tile), global::VectorTiles.Mvt.Tile.Parser, new[]{ "Layers" }, null, new[]{ typeof(global::VectorTiles.Mvt.Tile.Types.GeomType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::VectorTiles.Mvt.Tile.Types.Value), global::VectorTiles.Mvt.Tile.Types.Value.Parser, new[]{ "StringValue", "FloatValue", "DoubleValue", "IntValue", "UintValue", "SintValue", "BoolValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTiles.Mvt.Tile.Types.Feature), global::VectorTiles.Mvt.Tile.Types.Feature.Parser, new[]{ "Id", "Tags", "Type", "Geometry" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTiles.Mvt.Tile.Types.Layer), global::VectorTiles.Mvt.Tile.Types.Layer.Parser, new[]{ "Version", "Name", "Features", "Keys", "Values", "Extent" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class Tile : pb::IExtendableMessage<Tile>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Tile> _parser = new pb::MessageParser<Tile>(() => new Tile());
    private pb::UnknownFieldSet _unknownFields;
    private pb::ExtensionSet<Tile> _extensions;
    private pb::ExtensionSet<Tile> _Extensions { get { return _extensions; } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Tile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VectorTiles.Mvt.VectorTileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tile(Tile other) : this() {
      layers_ = other.layers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      _extensions = pb::ExtensionSet.Clone(other._extensions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Tile Clone() {
      return new Tile(this);
    }

    /// <summary>Field number for the "layers" field.</summary>
    public const int LayersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::VectorTiles.Mvt.Tile.Types.Layer> _repeated_layers_codec
        = pb::FieldCodec.ForMessage(26, global::VectorTiles.Mvt.Tile.Types.Layer.Parser);
    private readonly pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Layer> layers_ = new pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Layer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Layer> Layers {
      get { return layers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Tile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Tile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!layers_.Equals(other.layers_)) return false;
      if (!Equals(_extensions, other._extensions)) {
        return false;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= layers_.GetHashCode();
      if (_extensions != null) {
        hash ^= _extensions.GetHashCode();
      }
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      layers_.WriteTo(output, _repeated_layers_codec);
      if (_extensions != null) {
        _extensions.WriteTo(output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      layers_.WriteTo(ref output, _repeated_layers_codec);
      if (_extensions != null) {
        _extensions.WriteTo(ref output);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += layers_.CalculateSize(_repeated_layers_codec);
      if (_extensions != null) {
        size += _extensions.CalculateSize();
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Tile other) {
      if (other == null) {
        return;
      }
      layers_.Add(other.layers_);
      pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            }
            break;
          case 26: {
            layers_.AddEntriesFrom(input, _repeated_layers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            }
            break;
          case 26: {
            layers_.AddEntriesFrom(ref input, _repeated_layers_codec);
            break;
          }
        }
      }
    }
    #endif

    public TValue GetExtension<TValue>(pb::Extension<Tile, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<Tile, TValue> extension) {
      return pb::ExtensionSet.Get(ref _extensions, extension);
    }
    public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<Tile, TValue> extension) {
      return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
    }
    public void SetExtension<TValue>(pb::Extension<Tile, TValue> extension, TValue value) {
      pb::ExtensionSet.Set(ref _extensions, extension, value);
    }
    public bool HasExtension<TValue>(pb::Extension<Tile, TValue> extension) {
      return pb::ExtensionSet.Has(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::Extension<Tile, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }
    public void ClearExtension<TValue>(pb::RepeatedExtension<Tile, TValue> extension) {
      pb::ExtensionSet.Clear(ref _extensions, extension);
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Tile message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// GeomType is described in section 4.3.4 of the specification
      /// </summary>
      public enum GeomType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("POINT")] Point = 1,
        [pbr::OriginalName("LINESTRING")] Linestring = 2,
        [pbr::OriginalName("POLYGON")] Polygon = 3,
      }

      /// <summary>
      /// Variant type encoding
      /// The use of values is described in section 4.1 of the specification
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Value : pb::IExtendableMessage<Value>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
        private pb::UnknownFieldSet _unknownFields;
        private pb::ExtensionSet<Value> _extensions;
        private pb::ExtensionSet<Value> _Extensions { get { return _extensions; } }
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Value> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTiles.Mvt.Tile.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Value() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Value(Value other) : this() {
          _hasBits0 = other._hasBits0;
          stringValue_ = other.stringValue_;
          floatValue_ = other.floatValue_;
          doubleValue_ = other.doubleValue_;
          intValue_ = other.intValue_;
          uintValue_ = other.uintValue_;
          sintValue_ = other.sintValue_;
          boolValue_ = other.boolValue_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          _extensions = pb::ExtensionSet.Clone(other._extensions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Value Clone() {
          return new Value(this);
        }

        /// <summary>Field number for the "string_value" field.</summary>
        public const int StringValueFieldNumber = 1;
        private readonly static string StringValueDefaultValue = "";

        private string stringValue_;
        /// <summary>
        /// Exactly one of these values must be present in a valid message
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string StringValue {
          get { return stringValue_ ?? StringValueDefaultValue; }
          set {
            stringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "string_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasStringValue {
          get { return stringValue_ != null; }
        }
        /// <summary>Clears the value of the "string_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearStringValue() {
          stringValue_ = null;
        }

        /// <summary>Field number for the "float_value" field.</summary>
        public const int FloatValueFieldNumber = 2;
        private readonly static float FloatValueDefaultValue = 0F;

        private float floatValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float FloatValue {
          get { if ((_hasBits0 & 1) != 0) { return floatValue_; } else { return FloatValueDefaultValue; } }
          set {
            _hasBits0 |= 1;
            floatValue_ = value;
          }
        }
        /// <summary>Gets whether the "float_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasFloatValue {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "float_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearFloatValue() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "double_value" field.</summary>
        public const int DoubleValueFieldNumber = 3;
        private readonly static double DoubleValueDefaultValue = 0D;

        private double doubleValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double DoubleValue {
          get { if ((_hasBits0 & 2) != 0) { return doubleValue_; } else { return DoubleValueDefaultValue; } }
          set {
            _hasBits0 |= 2;
            doubleValue_ = value;
          }
        }
        /// <summary>Gets whether the "double_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDoubleValue {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "double_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDoubleValue() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "int_value" field.</summary>
        public const int IntValueFieldNumber = 4;
        private readonly static long IntValueDefaultValue = 0L;

        private long intValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long IntValue {
          get { if ((_hasBits0 & 4) != 0) { return intValue_; } else { return IntValueDefaultValue; } }
          set {
            _hasBits0 |= 4;
            intValue_ = value;
          }
        }
        /// <summary>Gets whether the "int_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasIntValue {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "int_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearIntValue() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "uint_value" field.</summary>
        public const int UintValueFieldNumber = 5;
        private readonly static ulong UintValueDefaultValue = 0UL;

        private ulong uintValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong UintValue {
          get { if ((_hasBits0 & 8) != 0) { return uintValue_; } else { return UintValueDefaultValue; } }
          set {
            _hasBits0 |= 8;
            uintValue_ = value;
          }
        }
        /// <summary>Gets whether the "uint_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasUintValue {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "uint_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearUintValue() {
          _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "sint_value" field.</summary>
        public const int SintValueFieldNumber = 6;
        private readonly static long SintValueDefaultValue = 0L;

        private long sintValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long SintValue {
          get { if ((_hasBits0 & 16) != 0) { return sintValue_; } else { return SintValueDefaultValue; } }
          set {
            _hasBits0 |= 16;
            sintValue_ = value;
          }
        }
        /// <summary>Gets whether the "sint_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasSintValue {
          get { return (_hasBits0 & 16) != 0; }
        }
        /// <summary>Clears the value of the "sint_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearSintValue() {
          _hasBits0 &= ~16;
        }

        /// <summary>Field number for the "bool_value" field.</summary>
        public const int BoolValueFieldNumber = 7;
        private readonly static bool BoolValueDefaultValue = false;

        private bool boolValue_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool BoolValue {
          get { if ((_hasBits0 & 32) != 0) { return boolValue_; } else { return BoolValueDefaultValue; } }
          set {
            _hasBits0 |= 32;
            boolValue_ = value;
          }
        }
        /// <summary>Gets whether the "bool_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasBoolValue {
          get { return (_hasBits0 & 32) != 0; }
        }
        /// <summary>Clears the value of the "bool_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearBoolValue() {
          _hasBits0 &= ~32;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Value);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Value other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (StringValue != other.StringValue) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
          if (IntValue != other.IntValue) return false;
          if (UintValue != other.UintValue) return false;
          if (SintValue != other.SintValue) return false;
          if (BoolValue != other.BoolValue) return false;
          if (!Equals(_extensions, other._extensions)) {
            return false;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasStringValue) hash ^= StringValue.GetHashCode();
          if (HasFloatValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue);
          if (HasDoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
          if (HasIntValue) hash ^= IntValue.GetHashCode();
          if (HasUintValue) hash ^= UintValue.GetHashCode();
          if (HasSintValue) hash ^= SintValue.GetHashCode();
          if (HasBoolValue) hash ^= BoolValue.GetHashCode();
          if (_extensions != null) {
            hash ^= _extensions.GetHashCode();
          }
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasStringValue) {
            output.WriteRawTag(10);
            output.WriteString(StringValue);
          }
          if (HasFloatValue) {
            output.WriteRawTag(21);
            output.WriteFloat(FloatValue);
          }
          if (HasDoubleValue) {
            output.WriteRawTag(25);
            output.WriteDouble(DoubleValue);
          }
          if (HasIntValue) {
            output.WriteRawTag(32);
            output.WriteInt64(IntValue);
          }
          if (HasUintValue) {
            output.WriteRawTag(40);
            output.WriteUInt64(UintValue);
          }
          if (HasSintValue) {
            output.WriteRawTag(48);
            output.WriteSInt64(SintValue);
          }
          if (HasBoolValue) {
            output.WriteRawTag(56);
            output.WriteBool(BoolValue);
          }
          if (_extensions != null) {
            _extensions.WriteTo(output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasStringValue) {
            output.WriteRawTag(10);
            output.WriteString(StringValue);
          }
          if (HasFloatValue) {
            output.WriteRawTag(21);
            output.WriteFloat(FloatValue);
          }
          if (HasDoubleValue) {
            output.WriteRawTag(25);
            output.WriteDouble(DoubleValue);
          }
          if (HasIntValue) {
            output.WriteRawTag(32);
            output.WriteInt64(IntValue);
          }
          if (HasUintValue) {
            output.WriteRawTag(40);
            output.WriteUInt64(UintValue);
          }
          if (HasSintValue) {
            output.WriteRawTag(48);
            output.WriteSInt64(SintValue);
          }
          if (HasBoolValue) {
            output.WriteRawTag(56);
            output.WriteBool(BoolValue);
          }
          if (_extensions != null) {
            _extensions.WriteTo(ref output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasStringValue) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
          }
          if (HasFloatValue) {
            size += 1 + 4;
          }
          if (HasDoubleValue) {
            size += 1 + 8;
          }
          if (HasIntValue) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(IntValue);
          }
          if (HasUintValue) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UintValue);
          }
          if (HasSintValue) {
            size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SintValue);
          }
          if (HasBoolValue) {
            size += 1 + 1;
          }
          if (_extensions != null) {
            size += _extensions.CalculateSize();
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Value other) {
          if (other == null) {
            return;
          }
          if (other.HasStringValue) {
            StringValue = other.StringValue;
          }
          if (other.HasFloatValue) {
            FloatValue = other.FloatValue;
          }
          if (other.HasDoubleValue) {
            DoubleValue = other.DoubleValue;
          }
          if (other.HasIntValue) {
            IntValue = other.IntValue;
          }
          if (other.HasUintValue) {
            UintValue = other.UintValue;
          }
          if (other.HasSintValue) {
            SintValue = other.SintValue;
          }
          if (other.HasBoolValue) {
            BoolValue = other.BoolValue;
          }
          pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                }
                break;
              case 10: {
                StringValue = input.ReadString();
                break;
              }
              case 21: {
                FloatValue = input.ReadFloat();
                break;
              }
              case 25: {
                DoubleValue = input.ReadDouble();
                break;
              }
              case 32: {
                IntValue = input.ReadInt64();
                break;
              }
              case 40: {
                UintValue = input.ReadUInt64();
                break;
              }
              case 48: {
                SintValue = input.ReadSInt64();
                break;
              }
              case 56: {
                BoolValue = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                }
                break;
              case 10: {
                StringValue = input.ReadString();
                break;
              }
              case 21: {
                FloatValue = input.ReadFloat();
                break;
              }
              case 25: {
                DoubleValue = input.ReadDouble();
                break;
              }
              case 32: {
                IntValue = input.ReadInt64();
                break;
              }
              case 40: {
                UintValue = input.ReadUInt64();
                break;
              }
              case 48: {
                SintValue = input.ReadSInt64();
                break;
              }
              case 56: {
                BoolValue = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

        public TValue GetExtension<TValue>(pb::Extension<Value, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<Value, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<Value, TValue> extension) {
          return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
        }
        public void SetExtension<TValue>(pb::Extension<Value, TValue> extension, TValue value) {
          pb::ExtensionSet.Set(ref _extensions, extension, value);
        }
        public bool HasExtension<TValue>(pb::Extension<Value, TValue> extension) {
          return pb::ExtensionSet.Has(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::Extension<Value, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::RepeatedExtension<Value, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }

      }

      /// <summary>
      /// Features are described in section 4.2 of the specification
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Feature : pb::IMessage<Feature>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Feature> _parser = new pb::MessageParser<Feature>(() => new Feature());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Feature> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTiles.Mvt.Tile.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Feature() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Feature(Feature other) : this() {
          _hasBits0 = other._hasBits0;
          id_ = other.id_;
          tags_ = other.tags_.Clone();
          type_ = other.type_;
          geometry_ = other.geometry_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Feature Clone() {
          return new Feature(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private readonly static ulong IdDefaultValue = 0UL;

        private ulong id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Id {
          get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
          set {
            _hasBits0 |= 1;
            id_ = value;
          }
        }
        /// <summary>Gets whether the "id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasId {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearId() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "tags" field.</summary>
        public const int TagsFieldNumber = 2;
        private static readonly pb::FieldCodec<uint> _repeated_tags_codec
            = pb::FieldCodec.ForUInt32(18);
        private readonly pbc::RepeatedField<uint> tags_ = new pbc::RepeatedField<uint>();
        /// <summary>
        /// Tags of this feature are encoded as repeated pairs of
        /// integers.
        /// A detailed description of tags is located in sections
        /// 4.2 and 4.4 of the specification
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<uint> Tags {
          get { return tags_; }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 3;
        private readonly static global::VectorTiles.Mvt.Tile.Types.GeomType TypeDefaultValue = global::VectorTiles.Mvt.Tile.Types.GeomType.Unknown;

        private global::VectorTiles.Mvt.Tile.Types.GeomType type_;
        /// <summary>
        /// The type of geometry stored in this feature.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::VectorTiles.Mvt.Tile.Types.GeomType Type {
          get { if ((_hasBits0 & 2) != 0) { return type_; } else { return TypeDefaultValue; } }
          set {
            _hasBits0 |= 2;
            type_ = value;
          }
        }
        /// <summary>Gets whether the "type" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasType {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "type" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearType() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "geometry" field.</summary>
        public const int GeometryFieldNumber = 4;
        private static readonly pb::FieldCodec<uint> _repeated_geometry_codec
            = pb::FieldCodec.ForUInt32(34);
        private readonly pbc::RepeatedField<uint> geometry_ = new pbc::RepeatedField<uint>();
        /// <summary>
        /// Contains a stream of commands and parameters (vertices).
        /// A detailed description on geometry encoding is located in 
        /// section 4.3 of the specification.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<uint> Geometry {
          get { return geometry_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Feature);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Feature other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if(!tags_.Equals(other.tags_)) return false;
          if (Type != other.Type) return false;
          if(!geometry_.Equals(other.geometry_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasId) hash ^= Id.GetHashCode();
          hash ^= tags_.GetHashCode();
          if (HasType) hash ^= Type.GetHashCode();
          hash ^= geometry_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasId) {
            output.WriteRawTag(8);
            output.WriteUInt64(Id);
          }
          tags_.WriteTo(output, _repeated_tags_codec);
          if (HasType) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Type);
          }
          geometry_.WriteTo(output, _repeated_geometry_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasId) {
            output.WriteRawTag(8);
            output.WriteUInt64(Id);
          }
          tags_.WriteTo(ref output, _repeated_tags_codec);
          if (HasType) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Type);
          }
          geometry_.WriteTo(ref output, _repeated_geometry_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasId) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
          }
          size += tags_.CalculateSize(_repeated_tags_codec);
          if (HasType) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          size += geometry_.CalculateSize(_repeated_geometry_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Feature other) {
          if (other == null) {
            return;
          }
          if (other.HasId) {
            Id = other.Id;
          }
          tags_.Add(other.tags_);
          if (other.HasType) {
            Type = other.Type;
          }
          geometry_.Add(other.geometry_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadUInt64();
                break;
              }
              case 18:
              case 16: {
                tags_.AddEntriesFrom(input, _repeated_tags_codec);
                break;
              }
              case 24: {
                Type = (global::VectorTile.Tile.Types.GeomType) input.ReadEnum();
                break;
              }
              case 34:
              case 32: {
                geometry_.AddEntriesFrom(input, _repeated_geometry_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Id = input.ReadUInt64();
                break;
              }
              case 18:
              case 16: {
                tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
                break;
              }
              case 24: {
                Type = (global::VectorTiles.Mvt.Tile.Types.GeomType) input.ReadEnum();
                break;
              }
              case 34:
              case 32: {
                geometry_.AddEntriesFrom(ref input, _repeated_geometry_codec);
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Layers are described in section 4.1 of the specification
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Layer : pb::IExtendableMessage<Layer>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Layer> _parser = new pb::MessageParser<Layer>(() => new Layer());
        private pb::UnknownFieldSet _unknownFields;
        private pb::ExtensionSet<Layer> _extensions;
        private pb::ExtensionSet<Layer> _Extensions { get { return _extensions; } }
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Layer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTiles.Mvt.Tile.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Layer() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Layer(Layer other) : this() {
          _hasBits0 = other._hasBits0;
          version_ = other.version_;
          name_ = other.name_;
          features_ = other.features_.Clone();
          keys_ = other.keys_.Clone();
          values_ = other.values_.Clone();
          extent_ = other.extent_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          _extensions = pb::ExtensionSet.Clone(other._extensions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Layer Clone() {
          return new Layer(this);
        }

        /// <summary>Field number for the "version" field.</summary>
        public const int VersionFieldNumber = 15;
        private readonly static uint VersionDefaultValue = 1;

        private uint version_;
        /// <summary>
        /// Any compliant implementation must first read the version
        /// number encoded in this message and choose the correct
        /// implementation for this version number before proceeding to
        /// decode other parts of this message.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Version {
          get { if ((_hasBits0 & 2) != 0) { return version_; } else { return VersionDefaultValue; } }
          set {
            _hasBits0 |= 2;
            version_ = value;
          }
        }
        /// <summary>Gets whether the "version" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasVersion {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "version" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearVersion() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private readonly static string NameDefaultValue = "";

        private string name_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_ ?? NameDefaultValue; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasName {
          get { return name_ != null; }
        }
        /// <summary>Clears the value of the "name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearName() {
          name_ = null;
        }

        /// <summary>Field number for the "features" field.</summary>
        public const int FeaturesFieldNumber = 2;
        private static readonly pb::FieldCodec<global::VectorTiles.Mvt.Tile.Types.Feature> _repeated_features_codec
            = pb::FieldCodec.ForMessage(18, global::VectorTiles.Mvt.Tile.Types.Feature.Parser);
        private readonly pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Feature> features_ = new pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Feature>();
        /// <summary>
        /// The actual features in this tile.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Feature> Features {
          get { return features_; }
        }

        /// <summary>Field number for the "keys" field.</summary>
        public const int KeysFieldNumber = 3;
        private static readonly pb::FieldCodec<string> _repeated_keys_codec
            = pb::FieldCodec.ForString(26);
        private readonly pbc::RepeatedField<string> keys_ = new pbc::RepeatedField<string>();
        /// <summary>
        /// Dictionary encoding for keys
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<string> Keys {
          get { return keys_; }
        }

        /// <summary>Field number for the "values" field.</summary>
        public const int ValuesFieldNumber = 4;
        private static readonly pb::FieldCodec<global::VectorTiles.Mvt.Tile.Types.Value> _repeated_values_codec
            = pb::FieldCodec.ForMessage(34, global::VectorTiles.Mvt.Tile.Types.Value.Parser);
        private readonly pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Value> values_ = new pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Value>();
        /// <summary>
        /// Dictionary encoding for values
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::VectorTiles.Mvt.Tile.Types.Value> Values {
          get { return values_; }
        }

        /// <summary>Field number for the "extent" field.</summary>
        public const int ExtentFieldNumber = 5;
        private readonly static uint ExtentDefaultValue = 4096;

        private uint extent_;
        /// <summary>
        /// Although this is an "optional" field it is required by the specification.
        /// See https://github.com/mapbox/vector-tile-spec/issues/47
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Extent {
          get { if ((_hasBits0 & 1) != 0) { return extent_; } else { return ExtentDefaultValue; } }
          set {
            _hasBits0 |= 1;
            extent_ = value;
          }
        }
        /// <summary>Gets whether the "extent" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasExtent {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "extent" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearExtent() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Layer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Layer other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Version != other.Version) return false;
          if (Name != other.Name) return false;
          if(!features_.Equals(other.features_)) return false;
          if(!keys_.Equals(other.keys_)) return false;
          if(!values_.Equals(other.values_)) return false;
          if (Extent != other.Extent) return false;
          if (!Equals(_extensions, other._extensions)) {
            return false;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasVersion) hash ^= Version.GetHashCode();
          if (HasName) hash ^= Name.GetHashCode();
          hash ^= features_.GetHashCode();
          hash ^= keys_.GetHashCode();
          hash ^= values_.GetHashCode();
          if (HasExtent) hash ^= Extent.GetHashCode();
          if (_extensions != null) {
            hash ^= _extensions.GetHashCode();
          }
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasName) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          features_.WriteTo(output, _repeated_features_codec);
          keys_.WriteTo(output, _repeated_keys_codec);
          values_.WriteTo(output, _repeated_values_codec);
          if (HasExtent) {
            output.WriteRawTag(40);
            output.WriteUInt32(Extent);
          }
          if (HasVersion) {
            output.WriteRawTag(120);
            output.WriteUInt32(Version);
          }
          if (_extensions != null) {
            _extensions.WriteTo(output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasName) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          features_.WriteTo(ref output, _repeated_features_codec);
          keys_.WriteTo(ref output, _repeated_keys_codec);
          values_.WriteTo(ref output, _repeated_values_codec);
          if (HasExtent) {
            output.WriteRawTag(40);
            output.WriteUInt32(Extent);
          }
          if (HasVersion) {
            output.WriteRawTag(120);
            output.WriteUInt32(Version);
          }
          if (_extensions != null) {
            _extensions.WriteTo(ref output);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasVersion) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
          }
          if (HasName) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          size += features_.CalculateSize(_repeated_features_codec);
          size += keys_.CalculateSize(_repeated_keys_codec);
          size += values_.CalculateSize(_repeated_values_codec);
          if (HasExtent) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Extent);
          }
          if (_extensions != null) {
            size += _extensions.CalculateSize();
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Layer other) {
          if (other == null) {
            return;
          }
          if (other.HasVersion) {
            Version = other.Version;
          }
          if (other.HasName) {
            Name = other.Name;
          }
          features_.Add(other.features_);
          keys_.Add(other.keys_);
          values_.Add(other.values_);
          if (other.HasExtent) {
            Extent = other.Extent;
          }
          pb::ExtensionSet.MergeFrom(ref _extensions, other._extensions);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                }
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                features_.AddEntriesFrom(input, _repeated_features_codec);
                break;
              }
              case 26: {
                keys_.AddEntriesFrom(input, _repeated_keys_codec);
                break;
              }
              case 34: {
                values_.AddEntriesFrom(input, _repeated_values_codec);
                break;
              }
              case 40: {
                Extent = input.ReadUInt32();
                break;
              }
              case 120: {
                Version = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                if (!pb::ExtensionSet.TryMergeFieldFrom(ref _extensions, ref input)) {
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                }
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                features_.AddEntriesFrom(ref input, _repeated_features_codec);
                break;
              }
              case 26: {
                keys_.AddEntriesFrom(ref input, _repeated_keys_codec);
                break;
              }
              case 34: {
                values_.AddEntriesFrom(ref input, _repeated_values_codec);
                break;
              }
              case 40: {
                Extent = input.ReadUInt32();
                break;
              }
              case 120: {
                Version = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

        public TValue GetExtension<TValue>(pb::Extension<Layer, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetExtension<TValue>(pb::RepeatedExtension<Layer, TValue> extension) {
          return pb::ExtensionSet.Get(ref _extensions, extension);
        }
        public pbc::RepeatedField<TValue> GetOrInitializeExtension<TValue>(pb::RepeatedExtension<Layer, TValue> extension) {
          return pb::ExtensionSet.GetOrInitialize(ref _extensions, extension);
        }
        public void SetExtension<TValue>(pb::Extension<Layer, TValue> extension, TValue value) {
          pb::ExtensionSet.Set(ref _extensions, extension, value);
        }
        public bool HasExtension<TValue>(pb::Extension<Layer, TValue> extension) {
          return pb::ExtensionSet.Has(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::Extension<Layer, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }
        public void ClearExtension<TValue>(pb::RepeatedExtension<Layer, TValue> extension) {
          pb::ExtensionSet.Clear(ref _extensions, extension);
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
